# -*- coding: utf-8 -*-
"""temperatureMonitoringSystem

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1voyW0U9bAd1-D7igusIB58UTZX9JdKgn
"""

import random
import time

# Taking input from user
min_temp = float(input("Enter minimum temperature limit: "))
max_temp = float(input("Enter maximum temperature limit: "))

print("Temperature Monitoring Started...\n")

while True:
    # Generate random temperature
    temperature = round(random.uniform(-10, 50), 2)

    print("Current Temperature:", temperature, "°C")

    # Compare temperature with limits
    if temperature < min_temp:
        print("Temperature is BELOW minimum limit!\n")
    elif temperature > max_temp:
        print("Temperature is ABOVE maximum limit!\n")
    else:
        print("Temperature is within safe limits.\n")

    # Wait for 2 seconds
    time.sleep(2)